import { coverageCommand } from './coverage.mjs';

/**
 * Generates the GitLab CI YAML for the quality gate.
 *
 * @param {object} config
 * @param {Set<string>}  config.checks
 * @param {string}       config.packageManager
 * @param {string|null}  config.testRunner
 * @param {string|null}  config.testCoverageScript
 * @param {string|null}  config.lintScript
 * @returns {string}
 */
export function generateGitlabWorkflow(config) {
  const {
    checks,
    packageManager: pm,
    testRunner,
    testCoverageScript,
    lintScript,
  } = config;

  const hasEslint      = checks.has('eslint');
  const hasCoverage    = checks.has('coverage');
  const hasDuplication = checks.has('duplication');
  const hasAudit       = checks.has('audit');
  const hasMutation    = checks.has('mutation');
  const hasComplexity  = checks.has('complexity');

  // Install and run commands per package manager
  let installCmd = 'npm ci';
  let runCmd = 'npm run';

  if (pm === 'pnpm') {
    installCmd = 'npm install -g pnpm && pnpm install --frozen-lockfile';
    runCmd = 'pnpm';
  } else if (pm === 'yarn') {
    installCmd = 'yarn install --frozen-lockfile';
    runCmd = 'yarn';
  } else if (pm === 'bun') {
    installCmd = 'npm install -g bun && bun install';
    runCmd = 'bun run';
  }

  // Cache configuration
  const cacheKey = pm === 'pnpm' ? 'pnpm-lock.yaml' : pm === 'yarn' ? 'yarn.lock' : 'package-lock.json';

  // Build job definitions
  const jobs = [];

  // --- lint job ---
  if (hasEslint) {
    const eslintRun = lintScript
      ? `${runCmd} ${lintScript} -- --format json --output-file reports/eslint.json || true`
      : `npx eslint . --format json --output-file reports/eslint.json || true`;

    jobs.push(`lint:
  stage: lint
  script:
    - mkdir -p reports
    - ${eslintRun}
  artifacts:
    paths:
      - reports/eslint.json
    expire_in: 1 week
    when: always`);
  }

  // --- test job ---
  if (hasCoverage) {
    const covScript = coverageCommand({ testRunner, runCmd, testCoverageScript });

    jobs.push(`test:
  stage: test
  script:
    - mkdir -p reports
    - ${covScript}
  artifacts:
    paths:
      - reports/coverage/
      - coverage/
    expire_in: 1 week
    when: always`);
  }

  // --- duplication job ---
  if (hasDuplication) {
    jobs.push(`duplication:
  stage: test
  script:
    - mkdir -p reports
    - npx jscpd . --ignore "node_modules,coverage,reports" --reporters json --output reports/ || true
  artifacts:
    paths:
      - reports/jscpd-report.json
    expire_in: 1 week
    when: always`);
  }

  // --- audit job ---
  if (hasAudit) {
    const auditCmd =
      pm === 'pnpm' ? 'pnpm audit --reporter json > reports/audit.json || true' :
      pm === 'yarn' ? 'yarn npm audit --json > reports/audit.json || true' :
      'npm audit --json > reports/audit.json || true';

    jobs.push(`audit:
  stage: test
  script:
    - mkdir -p reports
    - ${auditCmd}
  artifacts:
    paths:
      - reports/audit.json
    expire_in: 1 week
    when: always`);
  }

  // --- mutation job ---
  if (hasMutation) {
    jobs.push(`mutation:
  stage: test
  script:
    - mkdir -p reports/mutation
    - npx stryker run || true
  artifacts:
    paths:
      - reports/mutation/
    expire_in: 1 week
    when: always`);
  }

  // --- complexity job ---
  if (hasComplexity) {
    jobs.push(`complexity:
  stage: lint
  script:
    - mkdir -p reports
    - npx eslint . --rule '{"complexity":["warn",10],"max-lines-per-function":["warn",50]}' --format json --output-file reports/complexity.json || true
  artifacts:
    paths:
      - reports/complexity.json
    expire_in: 1 week
    when: always`);
  }

  // Determine stage dependencies for quality job
  const qualityNeeds = [];
  if (hasEslint) qualityNeeds.push('lint');
  if (hasComplexity) qualityNeeds.push('complexity');
  if (hasCoverage) qualityNeeds.push('test');
  if (hasDuplication) qualityNeeds.push('duplication');
  if (hasAudit) qualityNeeds.push('audit');
  if (hasMutation) qualityNeeds.push('mutation');

  const needsYaml = qualityNeeds.length > 0
    ? `  needs:\n${qualityNeeds.map((j) => `    - ${j}`).join('\n')}\n`
    : '';

  // --- quality gate job ---
  jobs.push(`quality-gate:
  stage: quality
${needsYaml}  script:
    - node scripts/quality-gate.mjs
  artifacts:
    paths:
      - reports/quality-gate-report.md
    expire_in: 1 week
    when: always
  allow_failure: false`);

  const jobsYaml = jobs.join('\n\n');

  return `# .gitlab-ci.yml — Generated by boatman
# https://github.com/rafaelvieiras/boatman
#
# This pipeline runs the quality gate on every push and MR.
# It compares metrics against baseline.json and blocks merges on regressions.

image: node:20-alpine

stages:
  - lint
  - test
  - quality

variables:
  NODE_ENV: test

cache:
  key:
    files:
      - ${cacheKey}
  paths:
    - node_modules/
  policy: pull-push

before_script:
  - ${installCmd}

${jobsYaml}
`;
}
